#!/bin/bash

echo "* Starting Node ..."
/usr/bin/digibyted -daemon -server=1 -testnet=1 -algo=scrypt -rpcuser=user -rpcpassword=pass -rpcport=16101 -rpcbind=0.0.0.0 -rpcallowip=::/0 -rpcssl=0

s6-svc -d /var/run/s6/services/node-pool
